#!/bin/bash -m

# script configuration
HOSTNAME_PREFIX=vibe-check-camera-
HOSTNAME_SUFFIX=.local
ROOT_NAME=camera

# automatically configured global variables
SSH_FILE="$HOME/.ssh/id_rsa"
SCRIPT=`basename "$0"`
if [ -z "$CAMERAS" ]; then
    CAMERAS="0 1 2 3 4 5 6 7 8 9 10 11"
fi

# check whether we are running under WSL
WSL=false
if grep -qEi "(microsoft|wsl)" /proc/version &> /dev/null ; then
    WSL=true
fi

function usage() {
    cat << EOF
./$SCRIPT

   Control all the cameras. Define CAMERAS to control a subset.

    help: print this message
    list: list all the camera ids
    set-hostname <ip> <id>: setup hostname and SSH at <ip> as camera <id>
    ssh-copy-id: copy SSH key from this machine to each camera
    ping: check connection to all cameras (uses SSH)
    exec: execute command via ssh on all cameras
    status: display info and recent logfile for all cameras
    shutdown: shutdown all cameras
    reboot: reboot all cameras
    update: rsync code and install arducam library on all cameras
    start: systemctl start vibecheck
    stop: systemctl stop vibecheck
    enable: systemctl enable vibecheck
    disable: systemctl disable vibecheck
EOF
   exit
}

function get_hostname() {
    echo $HOSTNAME_PREFIX$1
}

function get_address() {
    echo `get_hostname $1`$HOSTNAME_SUFFIX
}

function get_at() {
    ADDRESS=`get_address $1`
    if $WSL; then
        IP=`python3 resolve-dnsname.py vibe-check-camera-x.local`
        echo pi@$IP
    else
        echo pi@$ADDRESS
    fi
}

if [ $# -eq 0 ]; then
   usage
fi

# these are cases that do not require IDs
case "$1" in
help)
    usage
;;
list)
    for ID in $CAMERAS; do
        ADDRESS=`get_address $ID`
        AT=`get_at $ID`
        echo $ID $ADDRESS $AT
    done
    exit
esac

if [ ! -e "$SSH_FILE" ]; then
    echo "Couldn't find $SSH_FILE"
    exit
fi

# these are cases that operate on a specific device
case "$1" in
set-hostname)
    if [ "$#" -ne 3 ]; then
        echo "Example: ./$SCRIPT set-hostname 192.168.0.150 0"
        usage
    fi

    IP=$2
    NUMBER=$3
    AT=pi@$IP
    ssh-copy-id -i $SSH_FILE $AT
    HOSTNAME=$HOSTNAME_PREFIX$NUMBER
    # it takes four separate commands to fully set the hostname
    # "sudo: unable to resolve host..." is not an error, just intermediate
    # final command restarts the mdns server
    ssh $AT "sudo sed -i \"s/0\.1\.1.*/0.1.1\t$HOSTNAME/g\" /etc/hosts &&\
        sudo hostnamectl set-hostname $HOSTNAME &&\
        sudo hostname $HOSTNAME &&\
        echo $HOSTNAME | sudo tee /etc/hostname &&\
        sudo systemctl restart avahi-daemon"
;;
esac

# checking command validity
case "$1" in
    ping) ;;
    exec) ;;
    shutdown) ;;
    reboot) ;;
    update) ;;
    status) ;;
    pingtime) ;;
    enable) ;;
    start) ;;
    stop) ;;
    ssh-copy-id) ;;
    disable) ;;
    *)
        echo "Invalid command"
        usage
    ;;
esac

# sequential commands
for ID in $CAMERAS; do
    AT=`get_at $ID`
    case "$1" in
    ssh-copy-id)
        ssh-copy-id -i $SSH_FILE $AT
    ;;
    esac
done

# parallel commands
for ID in $CAMERAS; do
{
    ADDRESS=$HOSTNAME_PREFIX$ID$HOSTNAME_SUFFIX
    AT=pi@$ADDRESS
    if $WSL; then
        IP=`python3 resolve-dnsname.py vibe-check-camera-x.local`
        AT=pi@$IP
    fi
    
    # check if the device is online before continuing
    ssh -q \
        -o BatchMode=yes \
        -o StrictHostKeyChecking=no \
        -o ConnectTimeout=1 \
        $AT \
        'exit 0'
    if [ $? -ne 0 ]
    then
        echo "$ID $ADDRESS $AT offline"
        continue
    fi

    case "$1" in
    ping)
        echo $ID $ADDRESS $AT online
    ;;
    exec)
        ssh $AT "${@:2}"
    ;;
    shutdown)
        ssh $AT "/sbin/shutdown now"
    ;;
    reboot)
        ssh $AT "/sbin/shutdown --reboot now"
    ;;
    pingtime)
        HOSTNAME=$(hostname)
        ssh $AT 'RTT=`ping -c4 -i0.2 '$HOSTNAME'.local | grep rtt` &&\
            echo '$ADDRESS' $RTT'
    ;;
    status) 
        ssh $AT 'TEMP=`vcgencmd measure_temp|cut -d= -f2` &&\
            CPU_MEM=`ps --no-headers -eo cmd,%cpu,%mem --sort=-%cpu|head -n1|cut -d" " -f4-` &&\
            ACTIVE=`systemctl is-active vibecheck` &&\
            ERR_STATUS=`tail -n1 /var/log/vibecheck.err.log` &&\
            echo '$AT' $ACTIVE $TEMP $CPU_MEM $ERR_STATUS'
    ;;
    update)
        rsync -a \
            --exclude=.DS_Store \
            --exclude=__pycache__ \
            --delete \
            camera/ $AT:~/$ROOT_NAME/
        rsync -a config/$ID.json $AT:~/$ROOT_NAME/config.json
        ssh $AT 'sudo install -m 644 camera/libarducam_mipicamera.so /usr/lib/'
    ;;
    enable)
        ssh $AT "systemctl enable vibecheck"
    ;;
    start)
        ssh $AT "systemctl start vibecheck"
    ;;
    stop)
        ssh $AT "systemctl stop vibecheck"
    ;;
    disable)
        ssh $AT "systemctl disable vibecheck"
    ;;
    esac
} &
done
wait
